### Naive Bayes classfier
- Diabetes dataset

In [112]:
import numpy as np
import pandas as pd

In [113]:
# Load the dataset 
df = pd.read_csv('diabetes_dataset.csv')

In [114]:
# Print the first few records of the dataset
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [115]:
df.shape

(768, 9)

In [116]:
# Print the columns and datatype information of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [117]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [118]:
# Zero values are replaced with the mean values for these columns
Zero_not_acepted = ["Pregnancies", "Glucose","BloodPressure","SkinThickness","Insulin","BMI",
                    "DiabetesPedigreeFunction","Age"]

for column in Zero_not_acepted:
    df[column] = df[column].replace(0, np.NaN)
    mean = int(df[column].mean(skipna=True))
    df[column] = df[column].replace(np.NaN, mean)
    
    
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,155.0,33.6,0.627,50,1
1,1.0,85.0,66.0,29.0,155.0,26.6,0.351,31,0
2,8.0,183.0,64.0,29.0,155.0,23.3,0.672,32,1
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,4.0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2.0,122.0,70.0,27.0,155.0,36.8,0.340,27,0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1.0,126.0,60.0,29.0,155.0,30.1,0.349,47,1
767,1.0,93.0,70.0,31.0,155.0,30.4,0.315,23,0

In [119]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,155.0,33.6,0.627,50,1
1,1.0,85.0,66.0,29.0,155.0,26.6,0.351,31,0
2,8.0,183.0,64.0,29.0,155.0,23.3,0.672,32,1
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,4.0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [120]:
# Split the dataset into train data and test data
from sklearn.model_selection import train_test_split

X = df.iloc[:, 0:8]
y = df.iloc[:,8]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

#### Different types of Naive Bayes' Classfiers
1. Multinomial Naive Bayes
2. Bernoulli Naive Bayes
3. Gaussian Naive bayes

##### Multinomial Naive Bayes

In [121]:
from sklearn.naive_bayes import MultinomialNB

# Creata a multinomial clasifier 
MultiNomialModel = MultinomialNB()

# Traing the model using the training set
MultiNomialModel.fit(X_train, y_train)

# Predict on test data
y_pred = MultiNomialModel.predict(X_test)

In [122]:
# import confusion_matrix
from sklearn.metrics import confusion_matrix

# Evaluate Results
cm = confusion_matrix(y_test, y_pred)
cm

array([[107,  43],
       [ 43,  38]], dtype=int64)

In [123]:
# Accuracy score
from sklearn.metrics import accuracy_score

print('Multinomial Accuracy =', accuracy_score(y_test, y_pred))

Multinomial Accuracy = 0.6277056277056277

#### Bernoulli Naive Bayes

In [124]:
# Import Bernoulli model
from sklearn.naive_bayes import BernoulliNB

# Create the Bernoulli classifier model object
BernoulliModel = BernoulliNB()

# Train the model using the training data set
BernoulliModel.fit(X_train, y_train)

# Predcict on test data
y_pred = BernoulliModel.predict(X_test)

# Evaluate Results
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[150,   0],
       [ 81,   0]], dtype=int64)

In [125]:
# Find the accuracy score
from sklearn.metrics import accuracy_score

print('Bernoulli Accuracy =', accuracy_score(y_test, y_pred))

Bernoulli Accuracy = 0.6493506493506493

#### Gaussian Naive bayes

In [126]:
# Import Gaussian naive bayes' model 
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score

GaussianModel = GaussianNB()

GaussianModel.fit(X_train, y_train)

y_pred = GaussianModel.predict(X_test)

# Evaluate result


confusion_matrix(y_test, y_pred)

array([[119,  31],
       [ 33,  48]], dtype=int64)

In [127]:
print('Gaussian Accuracy =', accuracy_score(y_test, y_pred))

Gaussian Accuracy = 0.7229437229437229

Gaussian Naive Bayes model gives a better accuracy score